---
# PostgreSQL8.4のリポジトリをインストール
- name: install python-ssl
  yum: name=python-ssl state=present
- name: install PGDG RPM KEY
  rpm_key: state=present key=https://apt.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-84
- name: install PostgreSQL8.4 repository
  yum: name=http://yum.postgresql.org/8.4/redhat/rhel-5-x86_64/pgdg-centos-8.4-3.noarch.rpm state=present
# postgresqlのインストール
- name: install postgresql
  yum: name={{ item }} state=latest
  with_items:
  - postgresql-server
  - postgresql-contrib
# データディレクトリを準備
- name: make directory for dbroot 1
  file: path={{ dbroot }} state=directory owner=postgres group=postgres mode=700
- name: make directory for dbroot 2
  file: path={{ dbroot }}/data state=directory owner=postgres group=postgres mode=700
- name: make directory for dbroot 3
  file: path={{ dbroot }}/backups state=directory owner=postgres group=postgres mode=700
# PGDATAとPGLOGの設定
- name: create /etc/sysconfig/pgsql/postgresql
  template: src=postgresql.j2 dest=/etc/sysconfig/pgsql/postgresql owner=root group=root
# 自動起動の設定
- name: enable postgresql
  service: name=postgresql enabled=yes
# 設定済みかの確認
- name: check postgresql.conf
  command: test -f "{{ dbroot }}/data/postgresql.conf"
  register: result
  ignore_errors: true
# 初期化
- name: initdb
  command: su -l postgres -c "/usr/bin/initdb -E UNICODE --no-locale -D {{ dbroot }}/data"
  when: result|failed
- name: config pg_hba.conf
  template: src=pg_hba.conf.j2 dest={{ dbroot }}/data/pg_hba.conf
  when: result|failed
- name: config postgresql.conf
  copy: src=postgresql.conf dest={{ dbroot }}/data/postgresql.conf
  notify: restart postgresql
# サービス起動
- name: start postgresql
  service: name=postgresql state=started
# postgresユーザのパスワード初期化
- name: config postgres password
  command: /usr/bin/psql -U postgres -c "ALTER USER postgres with unencrypted password 'postgres';"
  when: result|failed
